---
abstract: 'provision hosting accounts on unix systems'
author:
  - 'Matt Simerson <msimerson@cpan.org>'
build_requires:
  Config: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300002, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Provision-Unix
requires:
  CPAN: 0
  Config::Tiny: 0
  Cwd: 0
  Data::Dumper: 0
  Date::Format: 0
  Digest::MD5: 1
  English: 0
  File::Basename: 0
  File::Copy: 0
  File::Path: 0
  File::Spec: 0
  File::stat: 0
  Getopt::Long: 2.37
  LWP::Simple: 0
  LWP::UserAgent: 0
  Params::Validate: 0.8
  Scalar::Util: 0
  Time::Local: 0
  URI: 0
  base: 0
  strict: 0
  utf8: 0
  vars: 0
  warnings: 0
version: 1.04
