---
abstract: 'provision hosting accounts on unix systems'
author:
  - 'Matt Simerson <msimerson@cpan.org>'
build_requires:
  Config: 0
  Quota: 0.1
  Test::More: 0.1
  Test::Perl::Critic: 0.1
  Test::Pod: 0.1
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300021, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Provision-Unix
requires:
  Apache::Admin::Config: 1
  Apache::ConfigFile: 1
  CPAN: 0
  Config::Tiny: 2
  Cwd: 0
  Data::Dumper: 0
  Date::Format: 0
  Digest::MD5: 1
  English: 0
  File::Basename: 0
  File::Copy: 0
  File::Path: 2.08
  File::Spec: 0
  File::stat: 0
  Getopt::Long: 2.37
  LWP::Simple: 0
  LWP::UserAgent: 0
  Mail::Send: 1
  Params::Validate: 0.8
  Quota: 0.1
  Scalar::Util: 0
  Time::Local: 0
  URI: 1
  base: 0
  strict: 0
  utf8: 1
  vars: 0
  warnings: 0
version: 1.06
