--- #YAML:1.0
name:               Provision-Unix
version:            0.35
abstract:           provision accounts on unix systems
author:
    - Matt Simerson <matt@tnpi.net>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Apache::Admin::Config:  0.9
    Config::Std:          0
    NicTool:              0
    Params::Validate:     0.8
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
