---
abstract: 'provision accounts on unix systems'
author:
  - msimerson@cpan.org
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Provision-Unix
no_index:
  directory:
    - inc
    - t
  file:
    - bin/remoteagent
recommends:
  Proc::ProcessTable: 0
  Test::Perl::Critic: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
requires:
  Config::Std: 0
  Getopt::Long: 2.37
  Params::Validate: 0.8
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.39
