---
abstract: 'provision hosting accounts on unix systems'
author:
  - 'Matt Simerson <msimerson@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300002, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Provision-Unix
requires:
  Config::Tiny: 0
  Digest::MD5: 1
  Getopt::Long: 2.37
  LWP::UserAgent: 0
  Params::Validate: 0.8
  URI: 0
version: 1.02
